# Generated by Django 3.2.18 on 2023-04-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20230322_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
